export const Languages = [
	"English",
	"Afrikaans",
	"Arabic",
	"Azerbaijani",
	"Bulgarian",
	"Bangla",
	"Bosnian",
	"Catalan",
	"Czech",
	"Danish",
	"German",
	"Greek",
	"English (Australia)",
	"English (United Kingdom)",
	"Spanish",
	"Spanish (Argentina)",
	"Spanish (Spain)",
	"Estonian",
	"Basque",
	"Finnish",
	"French",
	"French (Canada)",
	"Galician",
	"Hebrew",
	"Hindi",
	"Croatian",
	"Hungarian",
	"Indonesian",
	"Italian",
	"Japanese",
	"Georgian",
	"Kazakh",
	"Khmer",
	"Korean",
	"Lithuanian",
	"Latvian",
	"Macedonian",
	"Malay",
	"Norwegian Bokmål",
	"Dutch",
	"Polish",
	"Portuguese",
	"Portuguese (Portugal)",
	"Romanian",
	"Russian",
	"Slovak",
	"Slovenian",
	"Serbian",
	"Swedish",
	"Tamil",
	"Telugu",
	"Thai",
	"Filipino",
	"Turkish",
	"Ukrainian",
	"Vietnamese",
	"Simplified Chinese",
	"Traditional Chinese",
];

export enum LanguagesEnum {
	ENGLISH = "English",
	AFRIKAANS = "Afrikaans",
	ARABIC = "Arabic",
	AZERBAIJANI = "Azerbaijani",
	BULGARIAN = "Bulgarian",
	BANGLA = "Bangla",
	BOSNIAN = "Bosnian",
	CATALAN = "Catalan",
	CZECH = "Czech",
	DANISH = "Danish",
	GERMAN = "German",
	GREEK = "Greek",
	ENGLISHAUSTRALIA = "English (Australia)",
	ENGLISHUNITEDKINGDOM = "English (United Kingdom)",
	SPANISH = "Spanish",
	SPANISHARGENTINA = "Spanish (Argentina)",
	SPANISHSPAIN = "Spanish (Spain)",
	ESTONIAN = "Estonian",
	BASQUE = "Basque",
	FINNISH = "Finnish",
	FRENCH = "French",
	FRENCHCANADA = "French (Canada)",
	GALICIAN = "Galician",
	HEBREW = "Hebrew",
	HINDI = "Hindi",
	CROATIAN = "Croatian",
	HUNGARIAN = "Hungarian",
	INDONESIAN = "Indonesian",
	ITALIAN = "Italian",
	JAPANESE = "Japanese",
	GEORGIAN = "Georgian",
	KAZAKH = "Kazakh",
	KHMER = "Khmer",
	KOREAN = "Korean",
	LITHUANIAN = "Lithuanian",
	LATVIAN = "Latvian",
	MACEDONIAN = "Macedonian",
	MALAY = "Malay",
	NORWEGIANBOKMÅL = "Norwegian Bokmål",
	DUTCH = "Dutch",
	POLISH = "Polish",
	PORTUGUESE = "Portuguese",
	PORTUGUESEPORTUGAL = "Portuguese (Portugal)",
	ROMANIAN = "Romanian",
	RUSSIAN = "Russian",
	SLOVAK = "Slovak",
	SLOVENIAN = "Slovenian",
	SERBIAN = "Serbian",
	SWEDISH = "Swedish",
	TAMIL = "Tamil",
	TELUGU = "Telugu",
	THAI = "Thai",
	FILIPINO = "Filipino",
	TURKISH = "Turkish",
	UKRAINIAN = "Ukrainian",
	VIETNAMESE = "Vietnamese",
	SIMPLIFIEDCHINESE = "Simplified Chinese",
	TRADITIONALCHINESE = "Traditional Chinese",
}
