/* spellchecker: disable */

export const passions = [
	"90s Kid",
	"Harry Potter",
	"SoundCloud",
	"Spa",
	"Self Care",
	"Heavy Metal",
	"House Parties",
	"Gin tonic",
	"Gymnastics",
	"Ludo",
	"Maggi",
	"Hot Yoga",
	"Biryani",
	"Meditation",
	"Sushi",
	"Spotify",
	"Hockey",
	"Basketball",
	"Slam Poetry",
	"Home Workout",
	"Theater",
	"Cafe hopping",
	"Sneakers",
	"Aquarium",
	"Instagram",
	"Hot Springs",
	"Walking",
	"Running",
	"Travel",
	"Language Exchange",
	"Movies",
	"Guitarists",
	"Social Development",
	"Gym",
	"Social Media",
	"Hip Hop",
	"Skincare",
	"J-Pop",
	"Cricket",
	"Shisha",
	"Freelance",
	"K-Pop",
	"Skateboarding",
	"Gospel",
	"Potterhead",
	"Trying New Things",
	"Photography",
	"Bollywood",
	"Bhangra",
	"Reading",
	"Singing",
	"Sports",
	"Poetry",
	"Stand up Comedy",
	"Coffee",
	"Karaoke",
	"Fortnite",
	"Free Diving",
	"Self Development",
	"Mental Health Awareness",
	"Foodie Tour",
	"Voter Rights",
	"Jiu-jitsu",
	"Climate Change",
	"Exhibition",
	"Walking My Dog",
	"ghts",
	"Feminism",
	"VR Room",
	"Escape Cafe",
	"Shopping",
	"Brunch",
	"Investment",
	"Jetski",
	"Reggaeton",
	"Second-hand apparel",
	"Black Lives Matter",
	"Jogging",
	"Road Trips",
	"Vintage fashion",
	"Voguing",
	"Couchsurfing",
	"Happy hour",
	"Inclusivity",
	"Country Music",
	"Football",
	"Inline Skate",
	"Investing",
	"Tennis",
	"Ice Cream",
	"Ice Skating",
	"Human Rights",
	"Expositions",
	"Pig Roast",
	"Skiing",
	"Canoeing",
	"West End Musicals",
	"Snowboarding",
	"Pilates",
	"Pentathlon",
	"Broadway",
	"PlayStation",
	"Cheerleading",
	"Choir",
	"Pole Dancing",
	"Five-a-side Football",
	"Car Racing",
	"Pinterest",
	"Festivals",
	"Pub Quiz",
	"Catan",
	"Cosplay",
	"Motor Sports",
	"Coffee Stall",
	"Content Creation",
	"E-Sports",
	"Bicycle Racing",
	"Binge-Watching TV shows",
	"Songwriter",
	"Bodycombat",
	"Tattoos",
	"Painting",
	"Bodyjam",
	"Paddle Boarding",
	"Padel",
	"Blackpink",
	"Surfing",
	"Bowling",
	"Grime",
	"90s Britpop",
	"Bodypump",
	"Beach Bars",
	"Bodystep",
	"Paragliding",
	"Upcycling",
	"Equality",
	"Astrology",
	"Motorcycles",
	"Equestrian",
	"Entrepreneurship",
	"Sake",
	"BTS",
	"Cooking",
	"Environmental Protection",
	"Fencing",
	"Soccer",
	"Saxophonist",
	"Sci-Fi",
	"Dancing",
	"Film Festival",
	"Freeletics",
	"Gardening",
	"Amateur Cook",
	"Exchange Program",
	"Sauna",
	"Art",
	"Politics",
	"Flamenco",
	"Museum",
	"Activism",
	"DAOs",
	"Real Estate",
	"Podcasts",
	"Disability Rights",
	"Rave",
	"Pimms",
	"Drive Thru Cinema",
	"Rock Climbing",
	"BBQ",
	"Craft Beer",
	"Iced Tea",
	"Drummer",
	"Tea",
	"Board Games",
	"Roblox",
	"Pubs",
	"Rock",
	"Tango",
	"Drawing",
	"Trivia",
	"Pho",
	"Volunteering",
	"Environmentalism",
	"Rollerskating",
	"Wine",
	"Dungeons & Dragons",
	"Vlogging",
	"Electronic Music",
	"Ramen",
	"Weightlifting",
	"Live Music",
	"Writing",
	"Xbox",
	"World Peace",
	"Wrestling",
	"Literature",
	"Manga",
	"Pride",
	"Marathon",
	"Makeup",
	"Youth Empowerment",
	"YouTube",
	"Martial Arts",
	"Marvel",
	"Vegan Cooking",
	"Vermut",
	"Korean Food",
	"Twitter",
	"Volleyball",
	"Walking Tour",
	"Vinyasa",
	"Virtual Reality",
	"League of Legends",
	"NFTs",
	"Bar Hopping",
	"Nintendo",
	"Baseball",
	"Parties",
	"Ballet",
	"Band",
	"Online Games",
	"Battle Ground",
	"Beach Tennis",
	"Nightlife",
	"Online Shopping",
	"Sailing",
	"Olympic Gymnastics",
	"Bassist",
	"Online Broker",
	"Military",
	"Memes",
	"Among Us",
	"Motorbike Racing",
	"Motorcycling",
	"Metaverse",
	"Mindfulness",
	"Acapella",
	"Musical Instrument",
	"Art Galleries",
	"Musical Writing",
	"Hiking",
	"Artistic Gymnastics",
	"Mountains",
	"Archery",
	"Atari",
	"Backpacking",
	"Fishing",
	"Clubbing",
	"Street Food",
	"Crossfit",
	"Concerts",
	"Climbing",
	"Baking",
	"Camping",
	"Blogging",
	"Collecting",
	"Cars",
	"Start ups",
	"Boba tea",
	"High School Sports",
	"Badminton",
	"Active Lifestyle",
	"Fashion",
	"Anime",
	"NBA",
	"MLB",
	"Funk music",
	"Caipirinha",
	"Indoor Activities",
	"Tempeh",
	"DIY",
	"Town Festivities",
	"Cycling",
	"Outdoors",
	"TikTok",
	"Picnicking",
	"Twitch",
	"Comedy",
	"Trap Music",
	"Music",
	"Triathlon",
	"Netflix",
	"Disney",
	"Rugby",
	"Açaí",
	"Samba",
	"Tarot",
	"Stock Exchange",
	"Stocks",
	"Swimming",
	"Table Tennis",
	"Killing time",
	"Working out",
	"Yoga",
	"Horror Movies",
	"Boxing",
	"Bar Chilling",
];

export enum PassionsEnum {
	SKID90 = "90s Kid",
	HARRYPOTTER = "Harry Potter",
	SOUNDCLOUD = "SoundCloud",
	SPA = "Spa",
	SELFCARE = "Self Care",
	HEAVYMETAL = "Heavy Metal",
	HOUSEPARTIES = "House Parties",
	GINTONIC = "Gin tonic",
	GYMNASTICS = "Gymnastics",
	LUDO = "Ludo",
	MAGGI = "Maggi",
	HOTYOGA = "Hot Yoga",
	BIRYANI = "Biryani",
	MEDITATION = "Meditation",
	SUSHI = "Sushi",
	SPOTIFY = "Spotify",
	HOCKEY = "Hockey",
	BASKETBALL = "Basketball",
	SLAMPOETRY = "Slam Poetry",
	HOMEWORKOUT = "Home Workout",
	THEATER = "Theater",
	CAFEHOPPING = "Cafe hopping",
	SNEAKERS = "Sneakers",
	AQUARIUM = "Aquarium",
	INSTAGRAM = "Instagram",
	HOTSPRINGS = "Hot Springs",
	WALKING = "Walking",
	RUNNING = "Running",
	TRAVEL = "Travel",
	LANGUAGEEXCHANGE = "Language Exchange",
	MOVIES = "Movies",
	GUITARISTS = "Guitarists",
	SOCIALDEVELOPMENT = "Social Development",
	GYM = "Gym",
	SOCIALMEDIA = "Social Media",
	HIPHOP = "Hip Hop",
	SKINCARE = "Skincare",
	JPOP = "J-Pop",
	CRICKET = "Cricket",
	SHISHA = "Shisha",
	FREELANCE = "Freelance",
	KPOP = "K-Pop",
	SKATEBOARDING = "Skateboarding",
	GOSPEL = "Gospel",
	POTTERHEAD = "Potterhead",
	TRYINGNEWTHINGS = "Trying New Things",
	PHOTOGRAPHY = "Photography",
	BOLLYWOOD = "Bollywood",
	BHANGRA = "Bhangra",
	READING = "Reading",
	SINGING = "Singing",
	SPORTS = "Sports",
	POETRY = "Poetry",
	STANDUPCOMEDY = "Stand up Comedy",
	COFFEE = "Coffee",
	KARAOKE = "Karaoke",
	FORTNITE = "Fortnite",
	FREEDIVING = "Free Diving",
	SELFDEVELOPMENT = "Self Development",
	MENTALHEALTHAWARENESS = "Mental Health Awareness",
	FOODIETOUR = "Foodie Tour",
	VOTERRIGHTS = "Voter Rights",
	JIUJITSU = "Jiu-jitsu",
	CLIMATECHANGE = "Climate Change",
	EXHIBITION = "Exhibition",
	WALKINGMYDOG = "Walking My Dog",
	LGBTQRIGHTS = "ghts",
	FEMINISM = "Feminism",
	VRROOM = "VR Room",
	ESCAPECAFE = "Escape Cafe",
	SHOPPING = "Shopping",
	BRUNCH = "Brunch",
	INVESTMENT = "Investment",
	JETSKI = "Jetski",
	REGGAETON = "Reggaeton",
	SECONDHANDAPPAREL = "Second-hand apparel",
	BLACKLIVESMATTER = "Black Lives Matter",
	JOGGING = "Jogging",
	ROADTRIPS = "Road Trips",
	VINTAGEFASHION = "Vintage fashion",
	VOGUING = "Voguing",
	COUCHSURFING = "Couchsurfing",
	HAPPYHOUR = "Happy hour",
	INCLUSIVITY = "Inclusivity",
	COUNTRYMUSIC = "Country Music",
	FOOTBALL = "Football",
	INLINESKATE = "Inline Skate",
	INVESTING = "Investing",
	TENNIS = "Tennis",
	ICECREAM = "Ice Cream",
	ICESKATING = "Ice Skating",
	HUMANRIGHTS = "Human Rights",
	EXPOSITIONS = "Expositions",
	PIGROAST = "Pig Roast",
	SKIING = "Skiing",
	CANOEING = "Canoeing",
	WESTENDMUSICALS = "West End Musicals",
	SNOWBOARDING = "Snowboarding",
	PILATES = "Pilates",
	PENTATHLON = "Pentathlon",
	BROADWAY = "Broadway",
	PLAYSTATION = "PlayStation",
	CHEERLEADING = "Cheerleading",
	CHOIR = "Choir",
	POLEDANCING = "Pole Dancing",
	FIVEASIDEFOOTBALL = "Five-a-side Football",
	CARRACING = "Car Racing",
	PINTEREST = "Pinterest",
	FESTIVALS = "Festivals",
	PUBQUIZ = "Pub Quiz",
	CATAN = "Catan",
	COSPLAY = "Cosplay",
	MOTORSPORTS = "Motor Sports",
	COFFEESTALL = "Coffee Stall",
	CONTENTCREATION = "Content Creation",
	ESPORTS = "E-Sports",
	BICYCLERACING = "Bicycle Racing",
	BINGEWATCHINGTVSHOWS = "Binge-Watching TV shows",
	SONGWRITER = "Songwriter",
	BODYCOMBAT = "Bodycombat",
	TATTOOS = "Tattoos",
	PAINTING = "Painting",
	BODYJAM = "Bodyjam",
	PADDLEBOARDING = "Paddle Boarding",
	PADEL = "Padel",
	BLACKPINK = "Blackpink",
	SURFING = "Surfing",
	BOWLING = "Bowling",
	GRIME = "Grime",
	SBRITPOP90 = "90s Britpop",
	BODYPUMP = "Bodypump",
	BEACHBARS = "Beach Bars",
	BODYSTEP = "Bodystep",
	PARAGLIDING = "Paragliding",
	UPCYCLING = "Upcycling",
	EQUALITY = "Equality",
	ASTROLOGY = "Astrology",
	MOTORCYCLES = "Motorcycles",
	EQUESTRIAN = "Equestrian",
	ENTREPRENEURSHIP = "Entrepreneurship",
	SAKE = "Sake",
	BTS = "BTS",
	COOKING = "Cooking",
	ENVIRONMENTALPROTECTION = "Environmental Protection",
	FENCING = "Fencing",
	SOCCER = "Soccer",
	SAXOPHONIST = "Saxophonist",
	SCIFI = "Sci-Fi",
	DANCING = "Dancing",
	FILMFESTIVAL = "Film Festival",
	FREELETICS = "Freeletics",
	GARDENING = "Gardening",
	AMATEURCOOK = "Amateur Cook",
	EXCHANGEPROGRAM = "Exchange Program",
	SAUNA = "Sauna",
	ART = "Art",
	POLITICS = "Politics",
	FLAMENCO = "Flamenco",
	MUSEUM = "Museum",
	ACTIVISM = "Activism",
	DAOS = "DAOs",
	REALESTATE = "Real Estate",
	PODCASTS = "Podcasts",
	DISABILITYRIGHTS = "Disability Rights",
	RAVE = "Rave",
	PIMMS = "Pimms",
	DRIVETHRUCINEMA = "Drive Thru Cinema",
	ROCKCLIMBING = "Rock Climbing",
	BBQ = "BBQ",
	CRAFTBEER = "Craft Beer",
	ICEDTEA = "Iced Tea",
	DRUMMER = "Drummer",
	TEA = "Tea",
	BOARDGAMES = "Board Games",
	ROBLOX = "Roblox",
	PUBS = "Pubs",
	ROCK = "Rock",
	TANGO = "Tango",
	DRAWING = "Drawing",
	TRIVIA = "Trivia",
	PHO = "Pho",
	VOLUNTEERING = "Volunteering",
	ENVIRONMENTALISM = "Environmentalism",
	ROLLERSKATING = "Rollerskating",
	WINE = "Wine",
	DUNGEONSDRAGONS = "Dungeons & Dragons",
	VLOGGING = "Vlogging",
	ELECTRONICMUSIC = "Electronic Music",
	RAMEN = "Ramen",
	WEIGHTLIFTING = "Weightlifting",
	LIVEMUSIC = "Live Music",
	WRITING = "Writing",
	XBOX = "Xbox",
	WORLDPEACE = "World Peace",
	WRESTLING = "Wrestling",
	LITERATURE = "Literature",
	MANGA = "Manga",
	PRIDE = "Pride",
	MARATHON = "Marathon",
	MAKEUP = "Makeup",
	YOUTHEMPOWERMENT = "Youth Empowerment",
	YOUTUBE = "YouTube",
	MARTIALARTS = "Martial Arts",
	MARVEL = "Marvel",
	VEGANCOOKING = "Vegan Cooking",
	VERMUT = "Vermut",
	KOREANFOOD = "Korean Food",
	TWITTER = "Twitter",
	VOLLEYBALL = "Volleyball",
	WALKINGTOUR = "Walking Tour",
	VINYASA = "Vinyasa",
	VIRTUALREALITY = "Virtual Reality",
	LEAGUEOFLEGENDS = "League of Legends",
	NFTS = "NFTs",
	BARHOPPING = "Bar Hopping",
	NINTENDO = "Nintendo",
	BASEBALL = "Baseball",
	PARTIES = "Parties",
	BALLET = "Ballet",
	BAND = "Band",
	ONLINEGAMES = "Online Games",
	BATTLEGROUND = "Battle Ground",
	BEACHTENNIS = "Beach Tennis",
	NIGHTLIFE = "Nightlife",
	ONLINESHOPPING = "Online Shopping",
	SAILING = "Sailing",
	OLYMPICGYMNASTICS = "Olympic Gymnastics",
	BASSIST = "Bassist",
	ONLINEBROKER = "Online Broker",
	MILITARY = "Military",
	MEMES = "Memes",
	AMONGUS = "Among Us",
	MOTORBIKERACING = "Motorbike Racing",
	MOTORCYCLING = "Motorcycling",
	METAVERSE = "Metaverse",
	MINDFULNESS = "Mindfulness",
	ACAPELLA = "Acapella",
	MUSICALINSTRUMENT = "Musical Instrument",
	ARTGALLERIES = "Art Galleries",
	MUSICALWRITING = "Musical Writing",
	HIKING = "Hiking",
	ARTISTICGYMNASTICS = "Artistic Gymnastics",
	MOUNTAINS = "Mountains",
	ARCHERY = "Archery",
	ATARI = "Atari",
	BACKPACKING = "Backpacking",
	FISHING = "Fishing",
	CLUBBING = "Clubbing",
	STREETFOOD = "Street Food",
	CROSSFIT = "Crossfit",
	CONCERTS = "Concerts",
	CLIMBING = "Climbing",
	BAKING = "Baking",
	CAMPING = "Camping",
	BLOGGING = "Blogging",
	COLLECTING = "Collecting",
	CARS = "Cars",
	STARTUPS = "Start ups",
	BOBATEA = "Boba tea",
	HIGHSCHOOLSPORTS = "High School Sports",
	BADMINTON = "Badminton",
	ACTIVELIFESTYLE = "Active Lifestyle",
	FASHION = "Fashion",
	ANIME = "Anime",
	NBA = "NBA",
	MLB = "MLB",
	FUNKMUSIC = "Funk music",
	CAIPIRINHA = "Caipirinha",
	INDOORACTIVITIES = "Indoor Activities",
	TEMPEH = "Tempeh",
	DIY = "DIY",
	TOWNFESTIVITIES = "Town Festivities",
	CYCLING = "Cycling",
	OUTDOORS = "Outdoors",
	TIKTOK = "TikTok",
	PICNICKING = "Picnicking",
	TWITCH = "Twitch",
	COMEDY = "Comedy",
	TRAPMUSIC = "Trap Music",
	MUSIC = "Music",
	TRIATHLON = "Triathlon",
	NETFLIX = "Netflix",
	DISNEY = "Disney",
	RUGBY = "Rugby",
	AÇAÍ = "Açaí",
	SAMBA = "Samba",
	TAROT = "Tarot",
	STOCKEXCHANGE = "Stock Exchange",
	STOCKS = "Stocks",
	SWIMMING = "Swimming",
	TABLETENNIS = "Table Tennis",
	KILLINGTIME = "Killing time",
	WORKINGOUT = "Working out",
	YOGA = "Yoga",
	HORRORMOVIES = "Horror Movies",
	BOXING = "Boxing",
	BARCHILLING = "Bar Chilling",
}
