import UserEntity from "../entities/user.entity";
import { GenderEnum, ShowMeEnum } from "../types/user";

export const getAllUser = (): UserEntity[] => {
	const allUser = [
		{
			firstname: "Milan",
			lastname: "Koladiya",
			bio: "I am TS Lover",
			countryCode: "IN",
			aboutMe: "Similique ut quis ipsa fuga reprehenderit.",
			mobile: "2813665768",
			birthdate: "2002-03-17T09:04:14.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.MALE,
			email: "milan@nextgencode.com",
			password: "Milan@5432",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.238701080432097, 72.87941159670406],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "Tester",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: true,
			avatar: "https://www.pexels.com/photo/so-blue-15658217/",
			isCompOnBoarding: true,
		},
		{
			firstname: "JP",
			lastname: "Valadez",
			bio: "I am TS Lover",
			countryCode: "IN",
			aboutMe: "Facilis fugit iusto voluptatum minus inventore sed omnis ullam commodi.",
			mobile: "9267477888",
			birthdate: "2001-03-17T09:04:14.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.MALE,
			email: "jp@nextgencode.com",
			password: "JP@5432",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.238431076780696, 72.87936599915119],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "CEO",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: false,
			avatar: "https://www.pexels.com/photo/seagulls-flying-against-a-coastal-city-15679627/",
			isCompOnBoarding: true,
		},
		{
			firstname: "John",
			lastname: "Thether",
			bio: "I am TS Lover",
			countryCode: "IN",
			aboutMe: "Similique ut quis ipsa fuga reprehenderit.",
			mobile: "2813665769",
			birthdate: "2002-03-17T09:04:14.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.MALE,
			email: "john@nextgencode.com",
			password: "Milan@5432",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.23920608593414, 72.87823410695655],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "Software Developer",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: false,
			avatar:
				"https://images.pexels.com/photos/15549577/pexels-photo-15549577.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
			isCompOnBoarding: true,
		},
		{
			firstname: "Sarah",
			lastname: "Lee",
			bio: "I love hiking and reading",
			countryCode: "US",
			aboutMe: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non nulla risus.",
			mobile: "1234567890",
			birthdate: "1995-06-30T18:24:11.000Z",
			gender: GenderEnum.FEMALE,
			showMe: ShowMeEnum.MALE,
			email: "sarah.lee@gmail.com",
			password: "password123",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.23813857226696, 72.87830920880833],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "UCLA",
			boosts: 1,
			job: "Software Engineer",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 2,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: true,
			avatar: "https://www.pexels.com/photo/sea-city-landscape-beach-16144095/",
			isCompOnBoarding: true,
		},
		{
			firstname: "John",
			lastname: "Smith",
			bio: "I am a big fan of soccer",
			countryCode: "UK",
			aboutMe: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
			mobile: "447912345678",
			birthdate: "1988-11-12T13:44:22.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.FEMALE,
			email: "john.smith@yahoo.com",
			password: "mysecretpassword",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.239171085611737, 72.876914460123],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "Sales Manager",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 1,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: true,
			avatar: "https://www.pexels.com/photo/pizza-on-car-13302778/",
			isCompOnBoarding: true,
		},
		{
			firstname: "John",
			lastname: "Doe",
			bio: "I am a software engineer",
			countryCode: "US",
			aboutMe: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
			mobile: "555-1234",
			birthdate: "1990-01-01T00:00:00.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.FEMALE,
			email: "john.doe@example.com",
			password: "password123",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.23011822634192, 72.90914146526264],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "University of California",
			boosts: 0,
			job: "Software Engineer",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: false,
			avatar: "https://www.pexels.com/@gunas4life/",
			isCompOnBoarding: true,
		},
		{
			firstname: "Jane",
			lastname: "Doe",
			bio: "I am a graphic designer",
			countryCode: "US",
			aboutMe: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
			mobile: "555-5678",
			birthdate: "1992-02-02T00:00:00.000Z",
			gender: GenderEnum.FEMALE,
			showMe: ShowMeEnum.MALE,
			email: "jane.doe@example.com",
			password: "password456",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.129515996923175, 73.13201168779082],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "Parsons School of Design",
			boosts: 0,
			job: "Graphic Designer",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: true,
			avatar: "https://www.pexels.com/photo/person-holding-white-ceramic-mug-12548884/",
			isCompOnBoarding: true,
		},
		{
			firstname: "Bob",
			lastname: "Smith",
			bio: "I am a teacher",
			countryCode: "US",
			aboutMe: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
			mobile: "555-9012",
			birthdate: "1985-05-05T00:00:00.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.FEMALE,
			email: "bob.smith@example.com",
			password: "password789",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.55695010355823, 70.48389555547831],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "University of Illinois at Urbana-Champaign",
			boosts: 0,
			job: "Teacher",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: false,
			avatar: "https://www.pexels.com/photo/photograph-of-people-riding-an-amusement-park-ride-7118579/",
			isCompOnBoarding: true,
		},
		{
			firstname: "Emma",
			lastname: "Smith",
			bio: "I love to travel and try new foods!",
			countryCode: "US",
			aboutMe: "I'm a fun-loving person who enjoys meeting new people and trying new things.",
			mobile: "555-123-4567",
			birthdate: "1995-08-22T05:30:00.000Z",
			gender: GenderEnum.FEMALE,
			showMe: ShowMeEnum.MALE,
			email: "emma.smith@example.com",
			password: "Emma123!",
			blockedUsers: [],
			profileMedias: [],
			latLong: [24.98159374939803, 74.86527150754063],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "University of California, Berkeley",
			boosts: 3,
			job: "Software Engineer",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 1,
			darkMode: true,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: false,
			avatar: "https://www.pexels.com/photo/photograph-of-people-riding-an-amusement-park-ride-7118579/",
			isCompOnBoarding: true,
		},
		{
			firstname: "Jane",
			lastname: "Doe",
			bio: "I'm a coffee enthusiast and love trying new blends!",
			countryCode: "CA",
			aboutMe:
				"Etiam sagittis, tortor vitae fringilla placerat, eros neque posuere libero, et efficitur diam velit quis velit. In hac habitasse platea dictumst.",
			mobile: "9876543210",
			birthdate: "1995-11-02T08:00:00.000Z",
			gender: GenderEnum.FEMALE,
			showMe: ShowMeEnum.MALE,
			email: "jane.doe@example.com",
			password: "jane1234",
			blockedUsers: [],
			profileMedias: [],
			latLong: [22.93784095067491, 71.5993272480204],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "Marketing Manager",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: true,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: false,
			avatar:
				"https://images.pexels.com/photos/10665370/pexels-photo-10665370.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
			isCompOnBoarding: true,
		},
		{
			firstname: "Michael",
			lastname: "Scott",
			bio: "That's what she said.",
			countryCode: "US",
			aboutMe: "I declare bankruptcy!",
			mobile: "5551234567",
			birthdate: "1964-07-18T08:00:00.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.FEMALE,
			email: "michael.scott@example.com",
			password: "dundermifflin",
			blockedUsers: [],
			profileMedias: [],
			latLong: [23.320151440994593, 69.65003247392067],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "Regional Manager",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: true,
			avatar:
				"https://images.pexels.com/photos/16553909/pexels-photo-16553909.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
			isCompOnBoarding: true,
		},
		{
			firstname: "John",
			lastname: "Doe",
			bio: "I love hiking and reading",
			countryCode: "US",
			aboutMe: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
			mobile: "555-12348787",
			birthdate: "1995-07-22T04:00:00.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.FEMALE,
			email: "johndoe@example.com",
			password: "password123",
			blockedUsers: [],
			profileMedias: [],
			latLong: [28.617807107268998, 82.52976345504064],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "University of California",
			boosts: 0,
			job: "Software Engineer",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: false,
			avatar:
				"https://images.pexels.com/photos/16011243/pexels-photo-16011243.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
			isCompOnBoarding: true,
		},
		{
			firstname: "Alice",
			lastname: "Smith",
			bio: "I'm a coffee addict ☕️",
			countryCode: "CA",
			aboutMe: "Nullam et massa sit amet elit maximus suscipit.",
			mobile: "555-56783434",
			birthdate: "1993-05-18T04:00:00.000Z",
			gender: GenderEnum.FEMALE,
			showMe: ShowMeEnum.MALE,
			email: "alicesmith@example.com",
			password: "password456",
			blockedUsers: [],
			profileMedias: [],
			latLong: [29.666741446758675, 68.26572965783697],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "Marketing Manager",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: true,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: true,
			avatar:
				"https://images.pexels.com/photos/16542751/pexels-photo-16542751.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
			isCompOnBoarding: true,
		},
		{
			firstname: "Sam",
			lastname: "Lee",
			bio: "I'm a foodie 🍔🍟🍕",
			countryCode: "GB",
			aboutMe: "Vivamus facilisis augue eget dolor egestas, a pretium tellus lacinia.",
			mobile: "555-901223",
			birthdate: "1990-12-06T04:00:00.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.FEMALE,
			email: "samlee@example.com",
			password: "password789",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.235931375930015, 73.1805392304486],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "Chef",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: false,
			avatar:
				"https://images.pexels.com/photos/16350089/pexels-photo-16350089.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
			isCompOnBoarding: true,
		},
		{
			firstname: "John",
			lastname: "Doe",
			bio: "I love hiking and reading",
			countryCode: "US",
			aboutMe: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
			mobile: "555-1234-111",
			birthdate: "1995-07-22T04:00:00.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.FEMALE,
			email: "johndoe@example.com",
			password: "password123",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.19526456818568, 72.79224087747488],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "University of California",
			boosts: 0,
			job: "Software Engineer",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: true,
			avatar:
				"https://images.pexels.com/photos/11556100/pexels-photo-11556100.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
			isCompOnBoarding: true,
		},
		{
			firstname: "Alice",
			lastname: "Smith",
			bio: "I'm a coffee addict ☕️",
			countryCode: "CA",
			aboutMe: "Nullam et massa sit amet elit maximus suscipit.",
			mobile: "555-5678-222",
			birthdate: "1993-05-18T04:00:00.000Z",
			gender: GenderEnum.FEMALE,
			showMe: ShowMeEnum.MALE,
			email: "alicesmith@example.com",
			password: "password456",
			blockedUsers: [],
			profileMedias: [],
			latLong: [22.291496417738298, 73.17222883009295],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "Marketing Manager",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: true,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: true,
			avatar:
				"https://images.pexels.com/photos/16053708/pexels-photo-16053708.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
			isCompOnBoarding: true,
		},
		{
			firstname: "Sam",
			lastname: "Lee",
			bio: "I'm a foodie 🍔🍟🍕",
			countryCode: "GB",
			aboutMe: "Vivamus facilisis augue eget dolor egestas, a pretium tellus lacinia.",
			mobile: "555-9012-333",
			birthdate: "1990-12-06T04:00:00.000Z",
			gender: GenderEnum.MALE,
			showMe: ShowMeEnum.FEMALE,
			email: "samlee@example.com",
			password: "password789",
			blockedUsers: [],
			profileMedias: [],
			latLong: [21.215477252717175, 72.86228617188397],
			location: null,
			userInterestProfile: [],
			profileBoostDate: null,
			school: "",
			boosts: 0,
			job: "Chef",
			stripeUserId: "",
			subscriptionId: "",
			subscriptionsHistory: [],
			superLikes: 0,
			darkMode: false,
			darkModeDeviceSetting: false,
			stripeSubscriptionId: "",
			isVerified: false,
			avatar:
				"https://images.pexels.com/photos/16521872/pexels-photo-16521872.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
			isCompOnBoarding: true,
		},
	];

	return allUser.map((user:any) => ({
		...user,

		isCompOnBoarding: true,
		location: { type: "Point", coordinates: [user.latLong[1], user.latLong[0]] },
	}));
};
