import { DataSource } from "typeorm";
import { Seeder } from "typeorm-extension";
import SubscriptionsEntity, { SubscriptionsEnum } from "../entities/subscriptions.entity";

const subscriptions: SubscriptionsEntity[] = [
	{
		type: SubscriptionsEnum.PLUS,
		month: 1,
		currency: "$",
		amount: 7.99,
		stripeProductId: process.env.STRIPE_PLUS_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_PLUS_1MONTH_PRICE_ID,
		isUnlimitedLikes: true,
		seeWhoLikesYou: false,
		priorityLikes: false,
		UnlimitedRewinds: true,
		free1BoostPerMonth: false,
		free5SuperLikesPerWeek: false,
		messageBeforeMatching: false,
		passport: true,
		controlYourProfile: true,
		controlWhoSeesYou: true,
		controlWhoYouSee: true,
		HideAds: true,
	},
	{
		type: SubscriptionsEnum.PLUS,
		month: 6,
		currency: "$",
		amount: 24,
		stripeProductId: process.env.STRIPE_PLUS_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_PLUS_6MONTH_PRICE_ID,
		isUnlimitedLikes: true,
		seeWhoLikesYou: false,
		priorityLikes: false,
		UnlimitedRewinds: true,
		free1BoostPerMonth: false,
		free5SuperLikesPerWeek: false,
		messageBeforeMatching: false,
		passport: true,
		controlYourProfile: true,
		controlWhoSeesYou: true,
		controlWhoYouSee: true,
		HideAds: true,
	},
	{
		type: SubscriptionsEnum.PLUS,
		month: 12,
		currency: "$",
		amount: 32.04,
		stripeProductId: process.env.STRIPE_PLUS_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_PLUS_1YEAR_PRICE_ID,
		isUnlimitedLikes: true,
		seeWhoLikesYou: false,
		priorityLikes: false,
		UnlimitedRewinds: true,
		free1BoostPerMonth: false,
		free5SuperLikesPerWeek: false,
		messageBeforeMatching: false,
		passport: true,
		controlYourProfile: true,
		controlWhoSeesYou: true,
		controlWhoYouSee: true,
		HideAds: true,
	},
	{
		type: SubscriptionsEnum.GOLD,
		month: 1,
		currency: "$",
		amount: 24.99,
		stripeProductId: process.env.STRIPE_GOLD_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_GOLD_1MONTH_PRICE_ID,
		isUnlimitedLikes: true,
		seeWhoLikesYou: true,
		priorityLikes: false,
		UnlimitedRewinds: true,
		free1BoostPerMonth: true,
		free5SuperLikesPerWeek: true,
		messageBeforeMatching: false,
		passport: true,
		controlYourProfile: true,
		controlWhoSeesYou: true,
		controlWhoYouSee: true,
		HideAds: true,
	},
	{
		type: SubscriptionsEnum.GOLD,
		month: 6,
		currency: "$",
		amount: 75,
		stripeProductId: process.env.STRIPE_GOLD_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_GOLD_6MONTH_PRICE_ID,
		isUnlimitedLikes: true,
		seeWhoLikesYou: true,
		priorityLikes: false,
		UnlimitedRewinds: true,
		free1BoostPerMonth: true,
		free5SuperLikesPerWeek: true,
		messageBeforeMatching: false,
		passport: true,
		controlYourProfile: true,
		controlWhoSeesYou: true,
		controlWhoYouSee: true,
		HideAds: true,
	},
	{
		type: SubscriptionsEnum.GOLD,
		month: 12,
		currency: "$",
		amount: 99.96,
		stripeProductId: process.env.STRIPE_GOLD_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_GOLD_1YEAR_PRICE_ID,
		isUnlimitedLikes: true,
		seeWhoLikesYou: true,
		priorityLikes: false,
		UnlimitedRewinds: true,
		free1BoostPerMonth: true,
		free5SuperLikesPerWeek: true,
		messageBeforeMatching: false,
		passport: true,
		controlYourProfile: true,
		controlWhoSeesYou: true,
		controlWhoYouSee: true,
		HideAds: true,
	},
	{
		type: SubscriptionsEnum.PLATINUM,
		month: 1,
		currency: "$",
		amount: 29.99,
		stripeProductId: process.env.STRIPE_PLATINUM_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_PLATINUM_1MONTH_PRICE_ID,
		isUnlimitedLikes: true,
		seeWhoLikesYou: true,
		priorityLikes: true,
		UnlimitedRewinds: true,
		free1BoostPerMonth: true,
		free5SuperLikesPerWeek: true,
		messageBeforeMatching: true,
		passport: true,
		controlYourProfile: true,
		controlWhoSeesYou: true,
		controlWhoYouSee: true,
		HideAds: true,
	},
	{
		type: SubscriptionsEnum.PLATINUM,
		month: 6,
		currency: "$",
		amount: 90,
		stripeProductId: process.env.STRIPE_PLATINUM_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_PLATINUM_6MONTH_PRICE_ID,
		isUnlimitedLikes: true,
		seeWhoLikesYou: true,
		priorityLikes: true,
		UnlimitedRewinds: true,
		free1BoostPerMonth: true,
		free5SuperLikesPerWeek: true,
		messageBeforeMatching: true,
		passport: true,
		controlYourProfile: true,
		controlWhoSeesYou: true,
		controlWhoYouSee: true,
		HideAds: true,
	},
	{
		type: SubscriptionsEnum.PLATINUM,
		month: 12,
		currency: "$",
		amount: 120,
		stripeProductId: process.env.STRIPE_PLATINUM_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_PLATINUM_1YEAR_PRICE_ID,
		isUnlimitedLikes: true,
		seeWhoLikesYou: true,
		priorityLikes: true,
		UnlimitedRewinds: true,
		free1BoostPerMonth: true,
		free5SuperLikesPerWeek: true,
		messageBeforeMatching: true,
		passport: true,
		controlYourProfile: true,
		controlWhoSeesYou: true,
		controlWhoYouSee: true,
		HideAds: true,
	},
	{
		type: SubscriptionsEnum.BOOST,
		month: 3,
		currency: "$",
		amount: 5,
		stripeProductId: process.env.STRIPE_BOOST_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_BOOST_3_PRICE_ID,
		isUnlimitedLikes: false,
		seeWhoLikesYou: false,
		priorityLikes: false,
		UnlimitedRewinds: false,
		free1BoostPerMonth: false,
		free5SuperLikesPerWeek: false,
		messageBeforeMatching: false,
		passport: false,
		controlYourProfile: false,
		controlWhoSeesYou: false,
		controlWhoYouSee: false,
		HideAds: false,
	},
	{
		type: SubscriptionsEnum.BOOST,
		month: 10,
		currency: "$",
		amount: 12,
		stripeProductId: process.env.STRIPE_BOOST_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_BOOST_10_PRICE_ID,
		isUnlimitedLikes: false,
		seeWhoLikesYou: false,
		priorityLikes: false,
		UnlimitedRewinds: false,
		free1BoostPerMonth: false,
		free5SuperLikesPerWeek: false,
		messageBeforeMatching: false,
		passport: false,
		controlYourProfile: false,
		controlWhoSeesYou: false,
		controlWhoYouSee: false,
		HideAds: false,
	},
	{
		type: SubscriptionsEnum.BOOST,
		month: 20,
		currency: "$",
		amount: 18,
		stripeProductId: process.env.STRIPE_BOOST_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_BOOST_20_PRICE_ID,
		isUnlimitedLikes: false,
		seeWhoLikesYou: false,
		priorityLikes: false,
		UnlimitedRewinds: false,
		free1BoostPerMonth: false,
		free5SuperLikesPerWeek: false,
		messageBeforeMatching: false,
		passport: false,
		controlYourProfile: false,
		controlWhoSeesYou: false,
		controlWhoYouSee: false,
		HideAds: false,
	},
	{
		type: SubscriptionsEnum.SUPERLIKE,
		month: 3,
		currency: "$",
		amount: 5,
		stripeProductId: process.env.STRIPE_SUPERLIKE_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_SUPERLIKE_3_PRICE_ID,
		isUnlimitedLikes: false,
		seeWhoLikesYou: false,
		priorityLikes: false,
		UnlimitedRewinds: false,
		free1BoostPerMonth: false,
		free5SuperLikesPerWeek: false,
		messageBeforeMatching: false,
		passport: false,
		controlYourProfile: false,
		controlWhoSeesYou: false,
		controlWhoYouSee: false,
		HideAds: false,
	},
	{
		type: SubscriptionsEnum.SUPERLIKE,
		month: 15,
		currency: "$",
		amount: 12,
		stripeProductId: process.env.STRIPE_SUPERLIKE_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_SUPERLIKE_15_PRICE_ID,
		isUnlimitedLikes: false,
		seeWhoLikesYou: false,
		priorityLikes: false,
		UnlimitedRewinds: false,
		free1BoostPerMonth: false,
		free5SuperLikesPerWeek: false,
		messageBeforeMatching: false,
		passport: false,
		controlYourProfile: false,
		controlWhoSeesYou: false,
		controlWhoYouSee: false,
		HideAds: false,
	},
	{
		type: SubscriptionsEnum.SUPERLIKE,
		month: 30,
		currency: "$",
		amount: 22,
		stripeProductId: process.env.STRIPE_SUPERLIKE_PRODUCT_ID,
		stripePriceId: process.env.STRIPE_SUPERLIKE_30_PRICE_ID,
		isUnlimitedLikes: false,
		seeWhoLikesYou: false,
		priorityLikes: false,
		UnlimitedRewinds: false,
		free1BoostPerMonth: false,
		free5SuperLikesPerWeek: false,
		messageBeforeMatching: false,
		passport: false,
		controlYourProfile: false,
		controlWhoSeesYou: false,
		controlWhoYouSee: false,
		HideAds: false,
	},
];

export default class PassionSeeder implements Seeder {
	public async run(dataSource: DataSource): Promise<void> {
		await dataSource.createQueryBuilder().insert().into(SubscriptionsEntity).values(subscriptions).orIgnore().execute();
	}
}
